name: demystdata/semver-ecr
description: "A Buildkite plugin for semantic versioning with ECR"
author: "DemystData"
public: true
repository: "https://github.com/DemystData/semver-ecr-buildkite-plugin.git"
requirements: []
configuration:
  properties:
    repository:
      type: string
    region:
      type: string
    account:
      type: string
    version_branch:
      type: string
    initial_version:
      type: string
    tag_suffix:
      type: boolean
  required: 
    - repository
    - region
    - account
  additionalProperties: false