#!/bin/bash

set -uo pipefail

HOOKS_DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
export PATH="$PATH:$HOOKS_DIR/../bin"

AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

main() {

    export ENV_TEST=${AWS_ACCOUNT_ID}

}

main